# Generated by Django 3.2.8 on 2021-10-31 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='testing', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='media/default.jpg', upload_to='images/'),
        ),
    ]
